---
page_title: "Datafy Provider"
subcategory: ""
description: |-
  The Datafy provider is used to manage Datafy accounts, IAM role associations, access tokens, and autoscaling rules.
---

# Datafy Provider

The Datafy provider allows you to manage resources in your [Datafy](https://docs.datafy.io) organization using Terraform. Use this provider to create and manage accounts, associate AWS IAM roles, generate access tokens, and configure autoscaling rules.

## Prerequisites

- A Datafy organization account. Sign up at [datafy.io](https://docs.datafy.io) if you don't have one.
- A Datafy API token. See the [Token Generation](https://docs.datafy.io/set-up-and-installation/datafy-installation/token-generation) guide for instructions.

## Authentication

The provider requires an API token for authentication. You can provide the token in two ways:

1. **Provider configuration** — pass the token directly in your Terraform configuration. This is convenient for local experimentation, but is not recommended for production: the token will appear in plain text in any committed `.tf` files or shared modules, which is a credential leak risk.

```terraform
provider "datafy" {
  token = "your-api-token"
}
```

2. **Environment variable** (recommended) — set `DATAFY_TOKEN` in the environment where Terraform runs. This is the recommended approach for CI/CD pipelines and automation: the token is injected at runtime from your CI/CD secret store (e.g., GitHub Actions secrets, GitLab CI variables, AWS SSM, HashiCorp Vault) and never lands in your Terraform code or state files. It also lets you rotate the token without changing any `.tf` file.

```shell
export DATAFY_TOKEN="your-api-token"
```

```terraform
provider "datafy" {
}
```

## Example Usage

```terraform
terraform {
  required_providers {
    datafy = {
      source  = "datafy-io/datafy"
      version = "~> 1.1"
    }
  }
}

provider "datafy" {
  # Set DATAFY_TOKEN environment variable instead of hardcoding
}

# Create an account
resource "datafy_account" "example" {
  name = "my-account"
}

# Associate an AWS IAM role
resource "datafy_role_arn" "example" {
  account_id = datafy_account.example.id
  arn        = "arn:aws:iam::123456789012:role/DatafyRole"
}

# Create an access token
resource "datafy_token" "example" {
  account_id  = datafy_account.example.id
  description = "CI/CD pipeline token"
  ttl         = "24h"
  role_ids    = ["admin"]
}
```

<!-- schema generated by tfplugindocs -->
## Schema

### Optional

- `token` (String, Sensitive) Datafy API token used for authentication. Can also be configured using the `DATAFY_TOKEN` environment variable. See [Token Generation](https://docs.datafy.io/set-up-and-installation/datafy-installation/token-generation) for instructions on creating a token.
- `endpoint` (String) Datafy API endpoint. Can also be configured using the `DATAFY_ENDPOINT` environment variable. Defaults to `https://api.datafy.io`.
