name: check jira ticket format in commits

on:
  pull_request:

jobs:
  test_jira_ticket:
    runs-on: ubuntu-latest
    timeout-minutes: 5
    steps:
      - name: ignore-dependabot
        if: ${{ startsWith(github.head_ref, 'dependabot-') }}
        run: |

      - name: check-jira-ticket
        if: ${{ !startsWith(github.head_ref, 'dependabot-') }}
        run: |
          pr_name="${{ github.event.pull_request.title }}"
          if ! [[ $pr_name == *"DT-"* ]]; then
            echo "Pull request doesn't contain Jira ticket"
            exit 1
          fi
